### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by alexandersvozil** [schulzchristian/task_crunsher#1]
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: optimized
mpicxx -o optimized/app/task_crunsher.o -c -fopenmp -DNDEBUG -funroll-loops -Wall -fno-stack-limit -O3 -g -O3 -DNDEBUG -DPOINTER64=1 -Iextern/argtable-2.10/include -I/home/c_schulz/local/opt/boost/boost_1_48_0 app/task_crunsher.cpp
mpicxx -o optimized/lib/task_crunsher/task_crunsher.o -c -fopenmp -DNDEBUG -funroll-loops -Wall -fno-stack-limit -O3 -g -O3 -DNDEBUG -DPOINTER64=1 -Iextern/argtable-2.10/include -I/home/c_schulz/local/opt/boost/boost_1_48_0 lib/task_crunsher/task_crunsher.cpp
In file included from /usr/include/boost/filesystem/path.hpp:24:0,
                 from /usr/include/boost/process/operations.hpp:45,
                 from /usr/include/boost/process.hpp:42,
                 from lib/task_crunsher/task_crunsher.cpp:26:
/usr/include/boost/filesystem/config.hpp:16:5: error: #error Compiling Filesystem version 3 file with BOOST_FILESYSTEM_VERSION defined != 3
 error Compiling Filesystem version 3 file with BOOST_FILESYSTEM_VERSION defined != 3
     ^
In file included from /usr/include/boost/process.hpp:42:0,
                 from lib/task_crunsher/task_crunsher.cpp:26:
/usr/include/boost/process/operations.hpp: In function ‘std::__cxx11::string boost::process::find_executable_in_path(const string&, std::__cxx11::string)’:
/usr/include/boost/process/operations.hpp:85:36: error: ‘filesystem_error’ is not a member of ‘boost::filesystem’
             boost::throw_exception(boost::filesystem::filesystem_error("boost::process::find_executable_in_path: retrieving PATH fail
                                    ^
In file included from /usr/include/boost/process.hpp:42:0,
                 from lib/task_crunsher/task_crunsher.cpp:26:
/usr/include/boost/process/operations.hpp:130:32: error: ‘filesystem_error’ is not a member of ‘boost::filesystem’
         boost::throw_exception(boost::filesystem::filesystem_error("boost::process::find_executable_in_path: file not found", file, b
                                ^
scons: *** [optimized/lib/task_crunsher/task_crunsher.o] Error 1
scons: building terminated because of errors.
cp: cannot stat './optimized/task_crunsher': No such file or directory

**Comment by schulzchristian** [comment]
You have to install the correct boost files alex -- google will help you
(or i am next week).

**Comment by alexandersvozil** [comment]
Fixed these two errors by changing some define statement from 2 to 3 and changing some includes of the process library. Now I get this. 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: optimized
mpicxx -o optimized/app/task_crunsher.o -c -fopenmp -DNDEBUG -funroll-loops -Wall -fno-stack-limit -O3 -g -O3 -DNDEBUG -DPOINTER64=1 -Iextern/argtable-2.10/include -I/home/c_schulz/local/opt/boost/boost_1_48_0 app/task_crunsher.cpp
mpicxx -o optimized/lib/task_crunsher/task_crunsher.o -c -fopenmp -DNDEBUG -funroll-loops -Wall -fno-stack-limit -O3 -g -O3 -DNDEBUG -DPOINTER64=1 -Iextern/argtable-2.10/include -I/home/c_schulz/local/opt/boost/boost_1_48_0 lib/task_crunsher/task_crunsher.cpp
lib/task_crunsher/task_crunsher.cpp: In member function ‘void task_crunsher::run_task(std::__cxx11::string&)’:
lib/task_crunsher/task_crunsher.cpp:136:26: warning: variable ‘s’ set but not used [-Wunused-but-set-variable]
         bp::posix_status s  = c.wait();
                          ^
**mpicxx -o optimized/task_crunsher optimized/app/task_crunsher.o optimized/lib/task_crunsher/task_crunsher.o -Lextern/argtable-2.10/lib -L/home/c_schulz/local/opt/boost/boost_1_48_0/stage/lib -largtable2 -lboost_system -lboost_filesystem
optimized/lib/task_crunsher/task_crunsher.o: In function `MPI::Comm::Recv(void*, int, MPI::Datatype const&, int, int, MPI::Status&) const':
/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h:37: undefined reference to `MPI::INTEGER'
optimized/lib/task_crunsher/task_crunsher.o: In function `MPI::Comm::Send(void const*, int, MPI::Datatype const&, int, int) const':
/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h:30: undefined reference to `MPI::INTEGER'
optimized/lib/task_crunsher/task_crunsher.o: In function `task_crunsher::crunsh_tasks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/home/svozil/Dropbox/phd/task_crunsher/lib/task_crunsher/task_crunsher.cpp:77: undefined reference to `MPI::INTEGER'**
collect2: error: ld returned 1 exit status
scons: *** [optimized/task_crunsher] Error 1
scons: building terminated because of errors.
cp: cannot stat './optimized/task_crunsher': No such file or directory

**Comment by alexandersvozil** [comment]
Fixed that as well by setting the path to boost in the SConstruct  file.
